### ISSUE TITLE
Implement     std::vector<int> get_adjlist(WT_CURSOR *cursor, int node_id);

### ISSUE THREAD

**Issue by ameetrivedi** [artorhem/margraphita#31]
Implement     std::vector<int> get_adjlist(WT_CURSOR *cursor, int node_id);

**Comment by artorhem** [comment]
I think there's no need to pass the cursor in this function. We are using one global cursor to each of the table, and passing a cursor seems like unnecessary copy overhead during invocation.

**Comment by ameetrivedi** [comment]
I have one more question about which field to return after fetching the record because the In and Out table adjlist field has different names.

rest code added.

not closing the issue yet.

**Comment by artorhem** [comment]
In adj_common.h, there is a common adjlist struct defined.
Also, it should not matter what the table column name is; as long as the type of the column (S -- null terminated packed string) is the same, we can transparently use it.

**Comment by artorhem** [comment]
finished the implementation in commit a315f5bd3d321008de83e638a633fc5a8ef5a75e

**Comment by ameetrivedi** [comment]
Changed the return type... cursor record_to_adjlist is the entire adjlist struct we only need to return the vector<int> edgelist.
