### ISSUE TITLE
Implement     void add_to_adjlists(WT_CURSOR *cursor, int node_id, int to_insert);

### ISSUE THREAD

**Issue by ameetrivedi** [artorhem/margraphita#32]
Implement     void add_to_adjlists(WT_CURSOR *cursor, int node_id, int to_insert);

**Comment by ameetrivedi** [comment]
Code added but need to do a code walkthrough with Punnet.
We would need __record_to_adjlist and adjlist_to_record both.

**Comment by artorhem** [comment]
I don't know which commit it got fixed in, but fixed. :+1:
