### ISSUE TITLE
Implement     void delete_from_adjlists(WT_CURSOR *cursor, int node_id, int to_delete);

### ISSUE THREAD

**Issue by ameetrivedi** [artorhem/margraphita#33]
Implement     void delete_from_adjlists(WT_CURSOR *cursor, int node_id, int to_delete);

**Comment by ameetrivedi** [comment]
Added code and checked-in, not closing the issue, will discuss with Puneet before closing.

**Comment by artorhem** [comment]
I don't know which commit it was fixed in, but done :+1:
